name: validate from feature branch
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - main
jobs:
  validate-from-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz

          mkdir ~/sfdx

          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1

          echo "$HOME/sfdx/bin" >> $GITHUB_PATH

          ~/sfdx/bin/sfdx version
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.}} > ./.txt
      - name: Authenticate to target Org
        run: sfdx auth:sfdxurl:store -f ./.txt -s -a targetOrg
      - name: Installing java
        run: sudo apt-get update && sudo apt-get install default-jdk
      - name: Installing SFDX scanner
        run: sfdx plugins:install @salesforce/sfdx-scanner
      - name: Scan code
        run: sfdx scanner:run --format sarif --target './**/*.cls' --category
          'Design,Best Practices,Performance,Code Style,Security' --outfile
          'apexScanResults.sarif'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./apexScanResults.sarif
      - name: Deployment - run all tests
        run: >
          sfdx force:source:deploy -p "force-app" --checkonly --testlevel
          RunLocalTests --json
